# Generated by Django 5.1.7 on 2025-03-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='NAME_EDUCATION_TYPE_Academic_degree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='NAME_EDUCATION_TYPE_Higher_education',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='NAME_EDUCATION_TYPE_Incomplete_higher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='NAME_EDUCATION_TYPE_Lower_secondary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='NAME_EDUCATION_TYPE_Secondary_secondary_special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='NAME_INCOME_TYPE_Businessman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='NAME_INCOME_TYPE_Commercial_associate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='NAME_INCOME_TYPE_Pensioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='NAME_INCOME_TYPE_State_servant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='NAME_INCOME_TYPE_Student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='NAME_INCOME_TYPE_Unemployed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='NAME_INCOME_TYPE_Working',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='CODE_GENDER_M',
            field=models.BooleanField(default=False),
        ),
    ]
