# Generated by Django 5.1.7 on 2025-03-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_credit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('SK_ID_CURR', models.IntegerField(primary_key=True, serialize=False)),
                ('EXT_SOURCE_1', models.FloatField(blank=True, null=True)),
                ('EXT_SOURCE_2', models.FloatField(blank=True, null=True)),
                ('EXT_SOURCE_3', models.FloatField(blank=True, null=True)),
                ('DAYS_BIRTH', models.IntegerField()),
                ('DAYS_EMPLOYED', models.FloatField()),
                ('CODE_GENDER_M', models.BooleanField()),
                ('CREDIT_INCOME_PERCENT', models.FloatField()),
                ('ANNUITY_INCOME_PERCENT', models.FloatField()),
                ('CREDIT_TERM', models.FloatField()),
                ('AMT_CREDIT', models.FloatField()),
                ('AMT_ANNUITY', models.FloatField()),
                ('AMT_INCOME_TOTAL', models.FloatField()),
                ('DAYS_EMPLOYED_PERCENT', models.FloatField()),
            ],
        ),
    ]
