# Generated by Django 5.1.7 on 2025-04-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_credit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='NAME_EDUCATION_TYPE_Secondary_secondary_special',
        ),
        migrations.AddField(
            model_name='customer',
            name='CNT_CHILDREN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='LOAN_TYPE_Cash_0_or_Revolving_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='OWN_CAR_AGE',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='REG_REGION_NOT_WORK_REGION',
            field=models.IntegerField(default=0),
        ),
    ]
