# Generated by Django 5.1.7 on 2025-03-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_credit', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='EXT_SOURCE_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='EXT_SOURCE_2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='EXT_SOURCE_3',
            field=models.FloatField(),
        ),
    ]
