# Generated by Django 5.1.7 on 2025-04-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_credit', '0002_remove_customer_name_education_type_secondary_secondary_special_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='OWN_CAR_AGE',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='REG_REGION_NOT_WORK_REGION',
        ),
    ]
