# Generated by Django 5.1.7 on 2025-04-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_credit', '0003_remove_customer_own_car_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='OWN_CAR_AGE',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='REG_REGION_NOT_WORK_REGION',
            field=models.IntegerField(default=0),
        ),
    ]
